ignore_words = ['adamescu',
                'anamaria gavrilă',
                'arabia saudită',
                'bolnav',
                'bădulescu',
                'bărbat',
                'campion',
                'celorlalți',
                'ciorbă',
                'codruța kovesi',
                'colegă',
                'conferențiar',
                'consilier',
                'consilier parlamentar',
                'consilier politic',
                'constantinescu',
                'constanța',
                'crin antonescu',
                'cristela georgescu',
                'cristian terheș',
                'cîrstoiu',
                'călin georgescu',
                'căpitan',
                'cătălin drulă',
                'cătălin predoiu',
                'dacian cioloș',
                'dan nicușor',
                'daniel funeriu',
                'dansul',
                'diaconescu',
                'diana șoșoacă',
                'dinu patriciu',
                'dl georgescu',
                'dmitri peskov',
                'donald trump',
                'dragoș sprînceană',
                'dăncilă',
                'florin cîțu',
                'gavrilă',
                'geoană',
                'george becali',
                'georgescu călin',
                'goțiu',
                'guvernator',
                'guvernul ciolacu',
                'guvernul ciucă',
                'guvernul cîțu',
                'horațiu',
                'ilie bolojan',
                'iliescu',
                'inculpat',
                'ion iliescu',
                'ion rațiu',
                'ionescu',
                'ionuț vulpescu',
                'iulie',
                'laura vicol',
                'lavinia șandru',
                'lucian romașcanu',
                'marcel ciolacu',
                'mateescu',
                'mihail neamțu',
                'ministră',
                'miniștri',
                'mircea geoana',
                'mircea geoană',
                'netanyahu',
                'nicusor dan',
                'nicușor dan',
                'participanți',
                'activenews',
                'ajută',
                'abonați',
                'sprijiniți',
                'buletinul',
                'paul stănescu',
                'piatra neamț',
                'popescu piedone',
                'poporul',
                'prezidențiabil',
                'președinte interimar',
                'președintele interimar',
                'președintele româniei',
                'primăria',
                'părinte',
                'radu marinescu',
                'regală',
                'responsabil',
                'români',
                'roșu',
                'răzvan ungureanu',
                'simion nicușor',
                'sorin grindeanu',
                'susținătoare',
                'tăriceanu',
                'ungureanu',
                'valer dorneanu',
                'vicepreședinte',
                'vicepreședintele',
                'victor ciorbea',
                'victoria stoiciu',
                'viktor orban',
                'viorica dăncilă',
                'voiculescu',
                'șefă',
                'șerban nicolae',
                'șoșoacă',
                'înapoi homepage',
                'termenii condițiile',
                'traian basescu',
                'basescu',
                'articolul continuă',
                'conținutul website'
                'agerpres',
                'rugăm contactați',
                'contactați direcția',
                'secțiunea condiții',
                'exclusiv informării',
                'preluarea știrilor',
                'știrilor',
                'agerpres rugăm',
                'pagină',
                'știrile protv',
                'zilei',
                'publicația',
                'ziarul cotidianul',
                'rugăm trimiteți'
                ]
